---
name: Release to NuGet

'on':
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: self-hosted
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5

      - name: Get version from tag
        id: get_version
        run: |
          $tag = "${{ github.ref_name }}"
          $version = $tag -replace '^v', ''
          echo "version=$version" >> $env:GITHUB_OUTPUT
          echo "Version: $version"

      - name: Update project version
        run: |
          $version = "${{ steps.get_version.outputs.version }}"
          $propsFile = "src/Directory.Build.props"
          $content = Get-Content $propsFile -Raw
          $content = $content -replace '<Version>.*</Version>', "<Version>$version</Version>"
          Set-Content $propsFile -Value $content -Encoding UTF8
          Write-Host "Updated version to $version in Directory.Build.props"

      - name: Setup .NET
        uses: actions/setup-dotnet@v5

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build and Pack all targets
        run: |
          $artifactsPath = "${{ github.workspace }}\artifacts"
          New-Item -ItemType Directory -Force -Path $artifactsPath | Out-Null
          
          function BuildPack-MSBuild([string]$testProject, [string]$packProject, [string]$outputPath, [string]$name) {
            Write-Host "Building test project for $name..."
            msbuild $testProject '/t:Restore;Build' `
              /p:OutputPath="..\..\$outputPath\" `
              /p:Configuration=Release /p:Platform="Any CPU" /verbosity:minimal
            
            Write-Host "Packing $name..."
            msbuild $packProject '/t:Restore;Pack' `
              /p:OutputPath="..\..\$outputPath\" `
              /p:Configuration=Release /p:Platform="Any CPU" `
              /p:PackageOutputPath="$artifactsPath" /verbosity:minimal
            
            Write-Host "$name packed successfully."
          }
          
          function BuildPack-DotNet([string]$testProject, [string]$packProject, [string]$name) {
            Write-Host "Building test project for $name..."
            dotnet build $testProject --configuration Release
            
            Write-Host "Packing $name..."
            dotnet pack $packProject --configuration Release --output "$artifactsPath"
            
            Write-Host "$name packed successfully."
          }

          # AutoCAD 2019 - MSBuild (.NET Framework 4.8)
          BuildPack-MSBuild `
            "tests/TestAcad2019/TestAcad2019.csproj" `
            "src/Fs.Fox.AutoCad2019/Fs.Fox.AutoCad2019.csproj" `
            "Build\AC_2019_Release" `
            "AutoCAD 2019"

          # AutoCAD 2025 - dotnet CLI (.NET 8.0)
          BuildPack-DotNet `
            "tests/TestAcad2025/TestAcad2025.csproj" `
            "src/Fs.Fox.AutoCad2025/Fs.Fox.AutoCad2025.csproj" `
            "AutoCAD 2025"

          # ZWCAD 2022 - MSBuild (.NET Framework 4.8)
          BuildPack-MSBuild `
            "tests/TestZcad2022/TestZcad2022.csproj" `
            "src/Fs.Fox.ZwCad2022/Fs.Fox.ZwCad2022.csproj" `
            "Build\ZW_2022_Release" `
            "ZWCAD 2022"

          # ZWCAD 2025 - MSBuild (.NET Framework 4.8)
          BuildPack-MSBuild `
            "tests/TestZcad2025/TestZcad2025.csproj" `
            "src/Fs.Fox.ZwCad2025/Fs.Fox.ZwCad2025.csproj" `
            "Build\ZW_2025_Release" `
            "ZWCAD 2025"

      - name: Publish to NuGet
        run: |
          $packages = Get-ChildItem ./artifacts/*.nupkg
          foreach ($package in $packages) {
            Write-Host "Publishing $($package.Name)"
            dotnet nuget push $package.FullName `
              --api-key ${{ secrets.NUGET_API_KEY }} `
              --source https://api.nuget.org/v3/index.json `
              --skip-duplicate
          }

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Release ${{ github.ref_name }}

            ## 版本 / Version
            ${{ steps.get_version.outputs.version }}

            ## NuGet 包 / NuGet Packages
            - IFox.CAD.ACAD2019 (AutoCAD 2019, .NET Framework 4.8)
            - IFox.CAD.ACAD2025 (AutoCAD 2025, .NET 8.0)
            - IFox.CAD.ZCAD2022 (ZWCAD 2022, .NET Framework 4.8)
            - IFox.CAD.ZCAD2025 (ZWCAD 2025, .NET Framework 4.8)
          files: ./artifacts/*.nupkg
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.BUILD_REPO_TOKEN }}